config/routes.rb
Rails.application.routes.draw do
  get '/irish_census/counties', to: 'irish_census/counties#index'
  get '/irish_census/counties/:id', to: 'irish_census/counties#show', as: 'neo_county'
  get '/irish_census/deds/:id', to: 'irish_census/deds#show', as: 'neo_ded'
  get '/irish_census/townland_streets/:id', to: 'irish_census/townland_streets#show', as: 'neo_townland_street'
  get '/irish_census/houses/:id', to: 'irish_census/houses#show', as: 'neo_house'

  get '/irish_census/residents/:id', to: 'irish_census/residents#show', as: 'irish_census_resident'
  get '/irish_census/houses/:id', to: 'irish_census/houses#show', as: 'irish_census_house'
  get '/irish_census/houses_by_census/:census_id', to: 'irish_census/houses#show', as: 'irish_census_house_by_census_id'

  get '/irish_census/compare_candidate_houses_by_census/:census_id', to: 'irish_census/houses#compare_candidate_houses'

  get '/irish_census/houses/compare/:census_id_1/:census_id_2', to: 'irish_census/houses#compare'

  get '/irish_census/redirect_from_census_website', to: 'irish_census/main#redirect_from_census_website'

  put '/irish_census/residents/identify', to: 'irish_census/residents#identify'

  root 'irish_census/counties#index'
end

app/controllers/irish_census/counties_controller.rb
class IrishCensus::CountiesController < IrishCensus::GeoObjectsController
  def index
    @counties = Neo::County.all
  end

  def geo_object_class
    Neo::County
  end
end

app/controllers/irish_census/deds_controller.rb
class IrishCensus::DedsController < IrishCensus::GeoObjectsController
  def show
    ded = get_geo_object

    @title = "#{ded.name}"

    @residents_by_townland_street_uuid = {}
    @identified_by_townland_street_uuid = {}


    # ded.townland_streets(:townland_street).
    #   houses.
    #   residents.query_as(:resident).
    #   optional_match('resident-[i:identified_as]-(:Resident)').
    Neo4j::Session.query.match(ded: {DED: {uuid: ded.uuid}}).
      match('ded<-[:IN]-(townland_street:TownlandStreet)<-[:IN]-(:House)<-[:LIVES_IN]-(resident:Resident)').
      optional_match('resident-[i:identified_as]-(other_resident:Resident)').

      pluck('townland_street.uuid, count(resident), count(i)').each do |townland_street_uuid, resident_count, identified_count|
        @residents_by_townland_street_uuid[townland_street_uuid] = resident_count
        @identified_by_townland_street_uuid[townland_street_uuid] = identified_count
      end

    super
  end

  def geo_object_class
    Neo::DED
  end
end

app/controllers/irish_census/geo_objects_controller.rb
class IrishCensus::GeoObjectsController < ApplicationController
  def show
    @geo_object = get_geo_object
    render 'irish_census/geo_objects/show'
  end

  private

  def get_geo_objects
    geo_object_class.limit(200)
  end

  def get_geo_object
    geo_object_class.find(params[:id])
  end
end

app/controllers/irish_census/houses_controller.rb
class IrishCensus::HousesController < ApplicationController
  def show
    @house = get_house

    @title = "##{@house.house_number} - #{@house.census_year}"

    puts "request.referer", request.referer.inspect
  end

  def compare_candidate_houses
    @house = get_house
    @candidate_houses = @house.similar_houses
  end

  def compare
    @house1 = Neo::House.find(params[:census_id_1])
    @house2 = Neo::House.find(params[:census_id_2])
  end

  private

  def get_house
    if params[:census_id]
      Neo::House.where(census_id: params[:census_id].to_i).first
    else
      Neo::House.find(params[:id])
    end
  end
end

app/controllers/irish_census/main_controller.rb
class IrishCensus::MainController < ApplicationController
  def redirect_from_census_website
    # http://www.census.nationalarchives.ie/pages/1901/Antrim/Aghagallon/Aghadrumglosney/1002268/
    puts "request.referer", request.referer
    _, _, census_year, county, ded, townland_street, census_id = URI(request.referer).path.split('/')

    redirect_to irish_census_house_by_census_id_path(census_id)
  end
end

app/controllers/irish_census/residents_controller.rb
class IrishCensus::ResidentsController < ApplicationController
  def show
    @resident = Neo::Resident.find(params[:id])
  end

  def identify
    return render text: 'ERROR' if params[:source_id].blank? || params[:target_id].blank?

    source = Neo::Resident.find(params[:source_id])
    target = Neo::Resident.find(params[:target_id])

    case params[:type]
    when 'same'
      source.identify_as(target)
    when 'different'
      source.identify_as_not(target)
    when 'clear'
      source.clear_identified_as
    else
      raise "Invalid type param"
    end

    source = Neo::Resident.find(params[:source_id])
    render json: {same_identity: source.identified_as?(target)}
  end
end

app/controllers/irish_census/townland_streets_controller.rb
class IrishCensus::TownlandStreetsController < IrishCensus::GeoObjectsController
  def show
    townland_street = get_geo_object

    @title = "#{townland_street.name}"

    super
  end

  def geo_object_class
    Neo::TownlandStreet
  end
end

app/helpers/irish_census_helper.rb
module IrishCensusHelper
end

app/views/irish_census/houses/_comparison.html.slim
table.table.table-striped
  tr
    th &nbsp;
    th &nbsp;
    th
      = house2.townland_street.ded.county.name
      |  / 
      = house2.townland_street.ded.name
      |  / 
      = house2.townland_street.name
      |  / 
      = link_to "House ##{house2.house_number}", irish_census_house_path(house2)

  tr
    th = house1.census_year
    th &nbsp;
    th = house2.census_year

  - house1.match_residents(house2).each do |resident1, resident2|
    tr
      td = render partial: resident1 if resident1
      th
        - if resident1 && resident2
          - same_identity = resident1.identified_as?(resident2)
          = link_to 'Same', '#', class: "same-resident #{same_identity ? 'disabled' : ''}", data: {source_id: resident1.id, target_id: resident2.id, same_identity: same_identity}
          = link_to 'Clear', '#', class: 'clear-resident', data: {source_id: resident1.id, target_id: resident2.id}

      td = render partial: resident2 if resident2

app/views/irish_census/houses/compare.html.slim
= render partial: 'comparison', locals: {house1: @house1, house2: @house2}

app/views/irish_census/houses/compare_candidate_houses.html.erb
<h1>
  <%= @house.townland_street.ded.county.name %> /
  <%= @house.townland_street.ded.name %> /
  <%= @house.townland_street.name %> /
  <%= link_to "House ##{@house.house_number}", irish_census_house_path(@house) %>
</h1>

<% @candidate_houses.each do |candidate_house, count| %>
  <%= render partial: 'comparison', locals: {house1: @house, house2: candidate_house} %>
<% end %>

app/views/irish_census/houses/show.html.slim
h1
  = @house.townland_street.ded.county.name
  |  / 
  = link_to @house.townland_street.ded.name, @house.townland_street.ded
  |  / 
  = link_to @house.townland_street.name, @house.townland_street
  |  / #
  = @house.house_number

h2
  | Census Year:
  = @house.census_year
h2 Residents:

ul.list-group
  - @house.residents.sort_by {|r| r.age || 0 }.reverse.each do |resident|
    li.list-group-item = render partial: resident

.row
  = link_to 'Find similar houses', {action: :compare_candidate_houses, census_id: @house.census_id}, class: 'btn btn-primary'

  = irish_census_link 'Irish Census Page', @house, class: 'btn btn-primary'

.row
  input#compare-input.form-control type="text"
  button#compare.btn.btn-primary data-house-id="#{@house.id}" Compare